name: Sync with Upstream

on:
  repository_dispatch:
    types: [sync]
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Tags"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: devkimqwer/Front-Translate-Web
          token: ${{ secrets.FRONT_TRANSLATE_WEB }}
          fetch-depth: 0

      - name: Configure Git committer
        run: |
          git config --global user.name "devkimqwer github actions"
          git config --global user.email "devkimqwer@gmail.com"

      - name: Add remote repository
        run: git remote add upstream https://github.com/Transfolio-FE-2024/Front-Translate.git

      - name: Fetch upstream
        run: |
          git fetch upstream
          echo "Current branch: $(git branch)"

      - name: Merge upstream changes
        run: |
          git merge upstream/dev --allow-unrelated-histories
          git log --pretty=format:'%C(yellow)[%ad]%C(reset) %C(green)[%h]%C(reset) | %C(red)%s %C(bold red){{%an}}%C(reset) %C(blue)%d%C(reset)' --graph --date=short -1
        env:
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: github-actions@github.com

      - name: Push changes
        run: git push origin deploy
        env:
          GITHUB_TOKEN: ${{ secrets.FRONT_TRANSLATE_WEB }}
